"""Typed scientific contracts for countermovement-jump recovery forecasting."""

from importlib import import_module
from typing import TYPE_CHECKING, Any

from cmj_recovery_dynamics.contracts import (
    CANONICAL_OUTCOMES,
    FORCE_INNOVATION,
    NET_IMPULSE_INNOVATION,
    AggregationLevel,
    BenchmarkDefinition,
    CalibrationReferenceStatus,
    EvaluationDefinition,
    EvaluationImplementation,
    ForecastHorizon,
    MetricCategory,
    MetricUnits,
    MissingCellPolicy,
    NormalizationRule,
    OptimizationDirection,
    OutcomeDefinition,
    OutcomeVariable,
    PhysicalUnit,
    ProductionAcceptance,
    TargetCell,
    TaskDefinition,
    TaskType,
    WeightedOutcome,
    WeightingRule,
)
from cmj_recovery_dynamics.lineage.contracts import (
    ArtifactAvailability,
    ArtifactReference,
    BenchmarkApplicability,
    BenchmarkLineage,
    BenchmarkTransition,
    BootstrapProtocol,
    ChangeClass,
    ComparabilityConclusion,
    ConfigurationIdentity,
    ConfigurationStatus,
    ConflictDefinition,
    ConflictStatus,
    CoordinateBasis,
    DatasetIdentity,
    DatasetKind,
    EvaluationBinding,
    EvidenceConfidence,
    EvidenceReference,
    EvidenceStatus,
    ExperimentDefinition,
    ExperimentPurpose,
    ExperimentStatus,
    ModelFamily,
    ModelRole,
    PosteriorRMSETrace,
    ProtocolUnit,
    RedistributionStatus,
    RepresentationIdentity,
    ResultDefinition,
    ResultValue,
    ScientificDisposition,
    SplitIdentity,
    SplitRole,
    SplitUnit,
)
from cmj_recovery_dynamics.reproduction import get_reproduction_contract

if TYPE_CHECKING:
    from cmj_recovery_dynamics.lineage.registry import (
        LINEAGE_REGISTRY,
        BenchmarkLineageView,
        ExperimentLineageView,
        LineageRegistry,
        ModelLineageView,
        StudyLineage,
    )
    from cmj_recovery_dynamics.registry import (
        BENCHMARK_REGISTRY,
        EVALUATION_REGISTRY,
        TASK_REGISTRY,
        get_benchmark,
        get_benchmark_lineage,
        get_evaluation,
        get_experiment,
        get_experiment_lineage,
        get_model_family,
        get_model_lineage,
        get_result,
    )
    from cmj_recovery_dynamics.study_reconstruction import (
        EXPERIMENT_RECONSTRUCTIONS,
        STUDY_RECONSTRUCTIONS,
        ExperimentReconstruction,
        HistoricalDecisionRule,
        ProtocolCompleteness,
        ResultAuthority,
        SourceClosure,
        StudyClassification,
        StudyDecision,
        StudyReconstruction,
        get_experiment_reconstruction,
        get_study_reconstruction,
    )

__version__ = "0.1.0"

_LINEAGE_EXPORTS = frozenset(
    {
        "LINEAGE_REGISTRY",
        "BenchmarkLineageView",
        "ExperimentLineageView",
        "LineageRegistry",
        "ModelLineageView",
        "StudyLineage",
    }
)
_REGISTRY_EXPORTS = frozenset(
    {
        "BENCHMARK_REGISTRY",
        "EVALUATION_REGISTRY",
        "TASK_REGISTRY",
        "get_benchmark",
        "get_benchmark_lineage",
        "get_evaluation",
        "get_experiment",
        "get_experiment_lineage",
        "get_model_family",
        "get_model_lineage",
        "get_result",
    }
)
_STUDY_RECONSTRUCTION_EXPORTS = frozenset(
    {
        "EXPERIMENT_RECONSTRUCTIONS",
        "STUDY_RECONSTRUCTIONS",
        "ExperimentReconstruction",
        "HistoricalDecisionRule",
        "ProtocolCompleteness",
        "ResultAuthority",
        "SourceClosure",
        "StudyClassification",
        "StudyDecision",
        "StudyReconstruction",
        "get_experiment_reconstruction",
        "get_study_reconstruction",
    }
)


def __getattr__(name: str) -> Any:
    if name in _LINEAGE_EXPORTS:
        return getattr(import_module("cmj_recovery_dynamics.lineage.registry"), name)
    if name in _REGISTRY_EXPORTS:
        return getattr(import_module("cmj_recovery_dynamics.registry"), name)
    if name in _STUDY_RECONSTRUCTION_EXPORTS:
        return getattr(import_module("cmj_recovery_dynamics.study_reconstruction"), name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "BENCHMARK_REGISTRY",
    "LINEAGE_REGISTRY",
    "EVALUATION_REGISTRY",
    "CANONICAL_OUTCOMES",
    "FORCE_INNOVATION",
    "ForecastHorizon",
    "NET_IMPULSE_INNOVATION",
    "OutcomeDefinition",
    "OutcomeVariable",
    "PhysicalUnit",
    "TASK_REGISTRY",
    "BenchmarkDefinition",
    "BenchmarkApplicability",
    "BenchmarkLineage",
    "BenchmarkLineageView",
    "BootstrapProtocol",
    "ComparabilityConclusion",
    "ConflictDefinition",
    "CoordinateBasis",
    "EvidenceConfidence",
    "EvidenceReference",
    "EvaluationBinding",
    "ExperimentLineageView",
    "LineageRegistry",
    "ModelLineageView",
    "PosteriorRMSETrace",
    "ProtocolUnit",
    "RepresentationIdentity",
    "ResultValue",
    "StudyLineage",
    "BenchmarkTransition",
    "ChangeClass",
    "DatasetIdentity",
    "DatasetKind",
    "SplitIdentity",
    "SplitRole",
    "SplitUnit",
    "ModelFamily",
    "ModelRole",
    "ConfigurationIdentity",
    "ConfigurationStatus",
    "ArtifactReference",
    "ArtifactAvailability",
    "RedistributionStatus",
    "ExperimentDefinition",
    "ExperimentPurpose",
    "ExperimentStatus",
    "ResultDefinition",
    "EvidenceStatus",
    "ScientificDisposition",
    "ConflictStatus",
    "EvaluationDefinition",
    "EvaluationImplementation",
    "MetricCategory",
    "OptimizationDirection",
    "AggregationLevel",
    "NormalizationRule",
    "WeightingRule",
    "MissingCellPolicy",
    "MetricUnits",
    "ProductionAcceptance",
    "CalibrationReferenceStatus",
    "TargetCell",
    "WeightedOutcome",
    "TaskDefinition",
    "TaskType",
    "get_evaluation",
    "get_benchmark",
    "get_benchmark_lineage",
    "get_model_family",
    "get_model_lineage",
    "get_experiment",
    "get_experiment_lineage",
    "get_result",
    "get_reproduction_contract",
    "EXPERIMENT_RECONSTRUCTIONS",
    "STUDY_RECONSTRUCTIONS",
    "ExperimentReconstruction",
    "HistoricalDecisionRule",
    "ProtocolCompleteness",
    "ResultAuthority",
    "SourceClosure",
    "StudyClassification",
    "StudyDecision",
    "StudyReconstruction",
    "get_experiment_reconstruction",
    "get_study_reconstruction",
]
