"""Typed scientific contracts for countermovement-jump recovery forecasting."""

from cmj_recovery_dynamics.contracts import (
    CANONICAL_OUTCOMES,
    FORCE_INNOVATION,
    NET_IMPULSE_INNOVATION,
    AggregationLevel,
    BenchmarkDefinition,
    CalibrationReferenceStatus,
    EvaluationDefinition,
    EvaluationImplementation,
    ForecastHorizon,
    MetricCategory,
    MetricUnits,
    MissingCellPolicy,
    NormalizationRule,
    OptimizationDirection,
    OutcomeDefinition,
    OutcomeVariable,
    PhysicalUnit,
    ProductionAcceptance,
    TargetCell,
    TaskDefinition,
    TaskType,
    WeightedOutcome,
    WeightingRule,
)
from cmj_recovery_dynamics.registry import (
    BENCHMARK_REGISTRY,
    EVALUATION_REGISTRY,
    TASK_REGISTRY,
    get_evaluation,
)

__version__ = "0.1.0"

__all__ = [
    "BENCHMARK_REGISTRY",
    "EVALUATION_REGISTRY",
    "CANONICAL_OUTCOMES",
    "FORCE_INNOVATION",
    "ForecastHorizon",
    "NET_IMPULSE_INNOVATION",
    "OutcomeDefinition",
    "OutcomeVariable",
    "PhysicalUnit",
    "TASK_REGISTRY",
    "BenchmarkDefinition",
    "EvaluationDefinition",
    "EvaluationImplementation",
    "MetricCategory",
    "OptimizationDirection",
    "AggregationLevel",
    "NormalizationRule",
    "WeightingRule",
    "MissingCellPolicy",
    "MetricUnits",
    "ProductionAcceptance",
    "CalibrationReferenceStatus",
    "TargetCell",
    "WeightedOutcome",
    "TaskDefinition",
    "TaskType",
    "get_evaluation",
]
