"""Queryable M3 model and historical-result reproduction contracts."""

from .baselines import (
    LinearBaselineParameters,
    ModelInputError,
    ReferenceM0Parameters,
    fit_linear_public_baseline,
    predict_linear_public_baseline,
    predict_reference_m0,
    zero_innovation_prediction,
)
from .contracts import (
    CheckpointState,
    EvaluationReproduction,
    EvaluationRole,
    ModelConfigurationStatus,
    ModelReproduction,
    ModelReproductionStatus,
    ModelUseReproduction,
    ResultReplayAuthority,
    ResultReproduction,
    ResultReproductionStatus,
    SourceClosure,
    SpecimenModelLadder,
    SpecimenModelStatus,
)
from .evaluation import (
    EVALUATION_REPRODUCTIONS,
    get_evaluation_reproduction,
    require_production_scorer,
)
from .registry import (
    BENCHMARK_NAMES,
    MODEL_REPRODUCTIONS,
    RESULT_REPRODUCTIONS,
    SPECIMEN_MODEL_LADDERS,
    directly_comparable,
    get_model_reproduction,
    get_model_use_reproduction,
    get_result_reproduction,
    get_specimen_model_ladder,
)

__all__ = [
    "BENCHMARK_NAMES",
    "CheckpointState",
    "EVALUATION_REPRODUCTIONS",
    "EvaluationReproduction",
    "EvaluationRole",
    "LinearBaselineParameters",
    "MODEL_REPRODUCTIONS",
    "ModelConfigurationStatus",
    "ModelInputError",
    "ModelReproduction",
    "ModelReproductionStatus",
    "ModelUseReproduction",
    "RESULT_REPRODUCTIONS",
    "ReferenceM0Parameters",
    "ResultReplayAuthority",
    "ResultReproduction",
    "ResultReproductionStatus",
    "SPECIMEN_MODEL_LADDERS",
    "SourceClosure",
    "SpecimenModelLadder",
    "SpecimenModelStatus",
    "directly_comparable",
    "fit_linear_public_baseline",
    "get_evaluation_reproduction",
    "get_model_reproduction",
    "get_model_use_reproduction",
    "get_result_reproduction",
    "get_specimen_model_ladder",
    "predict_linear_public_baseline",
    "predict_reference_m0",
    "require_production_scorer",
    "zero_innovation_prediction",
]
